name: Perform Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC every day

env:
  ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
  ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}

jobs:
   build:
     name: ${{ matrix.os }}-${{ matrix.python-version }}
     if: github.repository == 'ARM-Development/radclss'
     runs-on: ${{ matrix.os }}-latest
     defaults:
        run:
          shell: bash -l {0}
     strategy:
        fail-fast: false
        matrix:
          python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
          os: [macOS, ubuntu]
          inlcude:
            - os: macos-latest
              PLAT: arm64
              INTERFACE64: ""
              platform: [x64]

     steps:
      - uses: actions/checkout@v5
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2.0.6
        with:
           create-args: python=${{ matrix.python-version }}
           environment-file: continuous-integration/environment-actions.yml
           micromamba-version: '2.0.0-0'
           environment-name: radclss_env
           cache-downloads: false

      - name: Install RadCLss
        shell: bash -l {0}
        run: |
          python -m pip install -e . --no-deps --force-reinstall

      - name: Lint with ruff
        shell: bash -l {0}
        run: |
          pip install ruff
          ruff check .

      - name: Test with pytest
        shell: bash -l {0}
        run: |
           pip install pytest
           python -m pytest -v --cov=./ --cov-report=xml

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v5.5.1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
